/**
 * Widget Definitions — все 29 виджетов дашборда
 *
 * Единый источник правды для метрик-карточек.
 * Группировка по категориям: sales, finance, ads, stocks, plan, delta.
 */
import {
  ShoppingBag,
  ShoppingCart,
  Package,
  DollarSign,
  Receipt,
  Megaphone,
  Banknote,
  TrendingUp,
  Percent,
  Truck,
  Warehouse,
  Target,
  Calculator,
  RotateCcw,
  PieChart,
  Boxes,
  CalendarClock,
  AlertTriangle,
  CreditCard,
  MousePointerClick,
  Scale,
  CheckCircle,
} from 'lucide-react';
import type { WidgetDefinition, WidgetCategory } from './registry';

// ==================== ALL 29 WIDGET DEFINITIONS ====================

export const WIDGET_DEFINITIONS: WidgetDefinition[] = [
  // ==================== SALES (ORDER-based) ====================
  {
    id: 'orders_count',
    title: 'Заказы',
    category: 'sales',
    axis: 'order',
    tooltipLines: ['Количество заказов за период', 'Данные по дате заказа (order-based)'],
    icon: ShoppingBag,
    accent: 'indigo',
    format: 'number',
    unit: 'шт',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'orders_revenue',
    title: 'Сумма заказов',
    mobileTitle: 'Заказы \u20BD',
    category: 'sales',
    axis: 'order',
    tooltipLines: ['Сумма всех заказов за период', 'Включает непроведённые заказы', 'Данные по дате заказа (order-based)'],
    icon: ShoppingCart,
    accent: 'indigo',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'sales_count',
    title: 'Выкупы (шт)',
    category: 'sales',
    axis: 'order',
    tooltipLines: ['Количество выкупленных товаров', 'Данные по дате заказа (order-based)'],
    icon: ShoppingCart,
    accent: 'emerald',
    format: 'number',
    unit: 'шт',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'returns_count',
    title: 'Возвраты',
    category: 'sales',
    axis: 'order',
    tooltipLines: ['Количество возвратов за период', 'Данные по дате заказа (order-based)'],
    icon: RotateCcw,
    accent: 'red',
    format: 'number',
    unit: 'шт',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'buyout_percent',
    title: 'Процент выкупа',
    mobileTitle: 'Выкуп %',
    category: 'sales',
    axis: 'order',
    tooltipLines: ['sales / orders \u00D7 100%', 'Доля выкупленных заказов', 'Данные по дате заказа (order-based)'],
    icon: Percent,
    accent: 'emerald',
    format: 'percent',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'avg_check',
    title: 'Средний чек',
    category: 'sales',
    axis: 'order',
    tooltipLines: ['revenue / sales_count', 'Данные по дате заказа (order-based)'],
    icon: Calculator,
    accent: 'indigo',
    format: 'currency',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'purchase_costs',
    title: 'Себестоимость',
    mobileTitle: 'Закупка',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['purchase_price \u00D7 settled_qty (Ozon) / sales_count (WB)', 'Себестоимость из Unit-экономики', 'Консистентна с осью выручки (settlement-based)'],
    icon: Package,
    accent: 'amber',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary', 'unitEconomics'],
  },

  // ==================== FINANCE (SETTLEMENT-based) ====================
  {
    id: 'revenue_settled',
    title: 'Выкупы (\u20BD)',
    mobileTitle: 'Выручка',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['Финализированная выручка из фин. отчёта', 'costs_tree \u201CПродажи\u201D + credits (WB)', 'Данные по дате фин. операции (settlement-based)'],
    icon: ShoppingCart,
    accent: 'emerald',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'payout',
    title: 'К перечислению',
    mobileTitle: 'Выплата',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['Сумма к перечислению от МП', 'total_accrued из финансового отчёта', 'Данные по дате фин. операции (settlement-based)', 'Оценка без задержки -- "Прибыль (оценка)"'],
    icon: Banknote,
    accent: 'sky',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'mp_deductions',
    title: 'Удержания МП',
    mobileTitle: 'Удержания',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['Комиссия + логистика + хранение + прочее', 'Из финансового отчёта МП', 'Данные по дате фин. операции (settlement-based)', 'Оценка без задержки -- "Удержания (заказы)"'],
    icon: Receipt,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'net_profit',
    title: 'Чистая прибыль',
    mobileTitle: 'Прибыль',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['payout - purchase - ads', 'Из Unit-экономики (settlement-based)', 'Совпадает со страницей UE'],
    icon: DollarSign,
    accent: 'emerald',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary', 'unitEconomics', 'costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'profit_margin',
    title: 'Рентабельность',
    mobileTitle: 'Рентаб. %',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['net_profit / revenue \u00D7 100%', 'Обе оси settlement-based', 'Совпадает со страницей UE'],
    icon: TrendingUp,
    accent: 'emerald',
    format: 'percent',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary', 'unitEconomics', 'costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'mp_commission',
    title: 'Комиссия МП',
    mobileTitle: 'Комиссия',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['Комиссия маркетплейса', 'Из costs_tree \u201CКомиссия\u201D', 'Данные по дате фин. операции (settlement-based)'],
    icon: CreditCard,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'mp_logistics',
    title: 'Логистика',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['Расходы на логистику МП', 'Из costs_tree \u201CЛогистика\u201D', 'Данные по дате фин. операции (settlement-based)'],
    icon: Truck,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'mp_storage',
    title: 'Хранение',
    category: 'finance',
    axis: 'settlement',
    tooltipLines: ['Расходы на хранение на складе МП', 'Из costs_tree \u201CХранение\u201D', 'Данные по дате фин. операции (settlement-based)'],
    icon: Warehouse,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['costsTreeOzon', 'costsTreeWb'],
  },

  // ==================== FINANCE (ORDER-based, из mp_orders) ====================
  {
    id: 'order_commission',
    title: 'Комиссия (заказы)',
    mobileTitle: 'Комисс. зак.',
    category: 'finance',
    axis: 'order',
    tooltipLines: [
      'Комиссия МП из позаказных данных',
      'Оценка из mp_orders (без задержки settlement)',
      'Точные данные — в виджете "Комиссия МП" (финансы)',
    ],
    icon: Scale,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['orderSummary'],
  },
  {
    id: 'order_logistics',
    title: 'Логистика (заказы)',
    mobileTitle: 'Логист. зак.',
    category: 'finance',
    axis: 'order',
    tooltipLines: [
      'Расходы на логистику из позаказных данных',
      'Оценка из mp_orders (без задержки settlement)',
      'Точные данные — в виджете "Логистика" (финансы)',
    ],
    icon: Truck,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['orderSummary'],
  },
  {
    id: 'order_deductions',
    title: 'Удержания (заказы)',
    mobileTitle: 'Удерж. зак.',
    category: 'finance',
    axis: 'order',
    tooltipLines: [
      'Все удержания МП из позаказных данных',
      'commission + logistics + storage + other_fees',
      'Оценка из mp_orders (без задержки settlement)',
      'Точные данные — в виджете "Удержания МП" (финансы)',
    ],
    icon: Receipt,
    accent: 'slate',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['orderSummary'],
  },
  {
    id: 'order_est_profit',
    title: 'Прибыль (оценка)',
    mobileTitle: 'Прибыль ~',
    category: 'finance',
    axis: 'order',
    tooltipLines: [
      'Оценочная прибыль из позаказных данных',
      'payout - purchase (payout уже за вычетом удержаний)',
      'Без задержки settlement (1-14 дней)',
      'Точные данные -- в виджете "Чистая прибыль" (финансы)',
    ],
    icon: DollarSign,
    accent: 'emerald',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['orderSummary'],
  },
  {
    id: 'settled_ratio',
    title: 'Проведено %',
    mobileTitle: 'Провед.',
    category: 'finance',
    axis: 'order',
    tooltipLines: [
      'Доля проведённых заказов',
      'settled_count / orders_count * 100%',
      'Показывает актуальность финансовых данных',
    ],
    icon: CheckCircle,
    accent: 'sky',
    format: 'percent',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['orderSummary'],
  },

  // ==================== ADS ====================
  {
    id: 'ad_cost',
    title: 'Реклама',
    category: 'ads',
    axis: 'ad',
    tooltipLines: ['Суммарные рекламные расходы', 'Данные по дате расхода'],
    icon: Megaphone,
    accent: 'violet',
    format: 'currency',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary'],
  },
  {
    id: 'drr',
    title: 'ДРР',
    category: 'ads',
    axis: 'mixed',
    tooltipLines: ['ad_cost / revenue \u00D7 100%', 'Доля рекламных расходов в выручке', 'Пересекает оси: ads / revenue (settlement)'],
    icon: PieChart,
    accent: 'violet',
    format: 'percent',
    defaultEnabled: true,
    tier: 'free',
    dataDeps: ['summary', 'costsTreeOzon', 'costsTreeWb'],
  },
  {
    id: 'acos',
    title: 'ACOS',
    category: 'ads',
    axis: 'ad',
    tooltipLines: ['Advertising Cost of Sale', 'Из данных рекламных кампаний', 'Данные по дате расхода'],
    icon: MousePointerClick,
    accent: 'violet',
    format: 'percent',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['adCosts'],
  },
  {
    id: 'cpo',
    title: 'CPO',
    mobileTitle: 'CPO \u20BD',
    category: 'ads',
    axis: 'ad',
    tooltipLines: ['Cost Per Order', 'ad_cost / orders_from_ads', 'Данные по дате расхода'],
    icon: MousePointerClick,
    accent: 'violet',
    format: 'currency',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['adCosts'],
  },

  // ==================== STOCKS (NEUTRAL) ====================
  {
    id: 'stock_total',
    title: 'Остатки (шт)',
    category: 'stocks',
    axis: 'neutral',
    tooltipLines: ['Суммарные остатки на всех складах', 'Текущее состояние (не за период)'],
    icon: Boxes,
    accent: 'sky',
    format: 'number',
    unit: 'шт',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['stocks'],
  },
  {
    id: 'stock_forecast_avg',
    title: 'Ср. запас дней',
    mobileTitle: 'Запас',
    category: 'stocks',
    axis: 'neutral',
    tooltipLines: ['Средний прогноз остатков в днях', 'quantity / avg_daily_sales(30d)', 'Текущее состояние (не за период)'],
    icon: CalendarClock,
    accent: 'sky',
    format: 'number',
    unit: 'дн.',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['stocks'],
  },
  {
    id: 'oos_count',
    title: 'Товары OOS',
    mobileTitle: 'OOS',
    category: 'stocks',
    axis: 'neutral',
    tooltipLines: ['Товары с нулевым остатком (Out of Stock)', 'Текущее состояние (не за период)'],
    icon: AlertTriangle,
    accent: 'red',
    format: 'number',
    unit: 'шт',
    defaultEnabled: false,
    tier: 'free',
    dataDeps: ['stocks'],
  },

  // ==================== PLAN (CALCULATED) ====================
  {
    id: 'plan_completion',
    title: 'Выполнение плана',
    mobileTitle: 'План',
    category: 'plan',
    axis: 'calculated',
    tooltipLines: ['Процент выполнения плана продаж', 'actual / plan \u00D7 100%', 'Только за месяцы с планом'],
    icon: Target,
    accent: 'indigo',
    format: 'percent',
    defaultEnabled: false,
    tier: 'pro',
    dataDeps: ['planCompletion'],
  },

  // ==================== DELTA (CALCULATED) ====================
  {
    id: 'period_delta',
    title: '\u0394 \u043A \u043F\u0440\u0435\u0434. \u043F\u0435\u0440\u0438\u043E\u0434\u0443',
    mobileTitle: 'Динамика',
    category: 'delta',
    axis: 'calculated',
    tooltipLines: ['Изменение выручки к предыдущему периоду', 'revenue_change_percent из summary'],
    icon: TrendingUp,
    accent: 'emerald',
    format: 'percent',
    defaultEnabled: true,
    tier: 'pro',
    dataDeps: ['summary'],
  },
];

// ==================== DERIVED COLLECTIONS ====================

/** Map по ID для быстрого доступа */
export const WIDGET_MAP = new Map<string, WidgetDefinition>(
  WIDGET_DEFINITIONS.map((w) => [w.id, w])
);

/** Список ID виджетов, включённых по умолчанию */
export const DEFAULT_ENABLED_WIDGETS: string[] = WIDGET_DEFINITIONS
  .filter((w) => w.defaultEnabled)
  .map((w) => w.id);

/** Виджеты, сгруппированные по категориям (для settings panel) */
export const WIDGETS_BY_CATEGORY: Record<WidgetCategory, WidgetDefinition[]> = WIDGET_DEFINITIONS.reduce(
  (acc, w) => {
    if (!acc[w.category]) {
      acc[w.category] = [];
    }
    acc[w.category].push(w);
    return acc;
  },
  {} as Record<WidgetCategory, WidgetDefinition[]>
);
